version: '3.8'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      - POSTGRES_HOST=host.docker.internal
    command: air main.go -b 0.0.0.0

volumes:
  postgres-db:
